---
title: "Untitled"
author: "Tim Majarian"
date: "11/6/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
## Sample_Stats. R
## Author: Jasen Jackson
## First version completed: 11/3/2017
## Goal: summarize characteristics of sample for poster presentations


## User specifies: trait file, cases, controls, and traits. 
# TODO: 1) Optimize parameter input process using command line args 
#       2) Make "traits" a parameter

## import ggplot and dataframe
library("ggplot2")
library(data.table)
ped.file <- "/Users/tmajaria/Downloads/Pooled_AFEU_WesselJ_25AUG2017_T2D_gtr_30.csv"
covars <- unlist(strsplit("last_exam_age,sex,last_exam_bmi,study_ancestry",","))
df <- fread(ped.file,sep="\t",header=T,stringsAsFactors=FALSE,showProgress=TRUE,data.table=FALSE)
# df <- read.table("Downloads/t2d.ped", header = T)

## remove rows with "NA" for traits of interest (BMI)
df = df[!is.na(df$last_exam_bmi),]
df = df[!is.na(df$last_exam_age),]

## define cases and controls .. split each by sex
df = df[df$T2D == 2 | df$T2D == 1 | df$T2D == 0,]
case = df[df$T2D == 2 | df$T2D == 1,]
control = df[df$T2D == 0,]

#males:
m = df[df$sex=="M",]
m_case = case[case$sex=="M",]
m_control = control[control$sex=="M",]

#females:
f = df[df$sex=="F",]
f_case = case[case$sex=="F",]
f_control = control[control$sex=="F",]

## Sample total for each group... 
print("Sample totals...")
nrow(df) # total in sample
nrow(case) # total # of cases (according to params)
nrow(control) # of controls
nrow(m) # total males
nrow(f) # total females
nrow(m_case) # total male cases
nrow(m_control) # total male controls
nrow(f_case) # total female cases
nrow(f_control) # total female controls

## In the future.. loop through each specified quantitative trait

### AGE ###

#-(Mean, median, std) age of each category
all_stats <- data.frame(matrix(NA, nrow = 3, ncol = length(covars)))
case_stats <- data.frame(matrix(NA, nrow = 3, ncol = length(covars)))
ctrl_stats <- data.frame(matrix(NA, nrow = 3, ncol = length(covars)))
m_stats <- data.frame(matrix(NA, nrow = 3, ncol = length(covars)))
f_stats <- data.frame(matrix(NA, nrow = 3, ncol = length(covars)))
mcase_stats <- data.frame(matrix(NA, nrow = 3, ncol = length(covars)))
mctrl_stats <- data.frame(matrix(NA, nrow = 3, ncol = length(covars)))
fcase_stats <- data.frame(matrix(NA, nrow = 3, ncol = length(covars)))
fctrl_stats <- data.frame(matrix(NA, nrow = 3, ncol = length(covars)))

colnames(all_stats) <- covars
colnames(case_stats) <- covars
colnames(ctrl_stats) <- covars
colnames(m_stats) <- covars
colnames(f_stats) <- covars
colnames(mcase_stats) <- covars
colnames(mctrl_stats) <- covars
colnames(fcase_stats) <- covars
colnames(fctrl_stats) <- covars

row.names(all_stats) <- c("mean","median","sd")
row.names(case_stats) <- c("mean","median","sd")
row.names(ctrl_stats) <- c("mean","median","sd")
row.names(m_stats) <- c("mean","median","sd")
row.names(f_stats) <- c("mean","median","sd")
row.names(mctrl_stats) <- c("mean","median","sd")
row.names(mcase_stats) <- c("mean","median","sd")
row.names(fcase_stats) <- c("mean","median","sd")
row.names(fctrl_stats) <- c("mean","median","sd")

```

```{r,fig.height=4,fig.width=6}
layout(matrix(seq(1,6*(length(covars)-1)),nrow=length(covars)-1,ncol=6,byrow=T))
for (i in covars){
  if (i != "study_ancestry" & i != "STUDY_ANCESTRY" & i != "sex"){
  print(i)
  all_stats[1,i] <- mean(df[,i])
  all_stats[2,i] <- median(df[,i])
  all_stats[3,i] <- sd(df[,i])
  
  case_stats[1,i] <- mean(case[,i])
  case_stats[2,i] <- median(case[,i])
  case_stats[3,i] <- sd(case[,i])
  
  ctrl_stats[1,i] <- mean(control[,i])
  ctrl_stats[2,i] <- median(control[,i])
  ctrl_stats[3,i] <- sd(control[,i])
  
  m_stats[1,i] <- mean(m[,i])
  m_stats[2,i] <- median(m[,i])
  m_stats[3,i] <- sd(m[,i])
  
  f_stats[1,i] <- mean(f[,i])
  f_stats[2,i] <- median(f[,i])
  f_stats[3,i] <- sd(f[,i])
  
  mcase_stats[1,i] <- mean(m_case[,i])
  mcase_stats[2,i] <- median(m_case[,i])
  mcase_stats[3,i] <- sd(m_case[,i])
  
  mctrl_stats[1,i] <- mean(m_control[,i])
  mctrl_stats[2,i] <- median(m_control[,i])
  mctrl_stats[3,i] <- sd(m_control[,i])
  
  fcase_stats[1,i] <- mean(f_case[,i])
  fcase_stats[2,i] <- median(f_case[,i])
  fcase_stats[3,i] <- sd(f_case[,i])
  
  fctrl_stats[1,i] <- mean(f_control[,i])
  fctrl_stats[2,i] <- median(f_control[,i])
  fctrl_stats[3,i] <- sd(f_control[,i])
  
    plot <- ggplot(df, aes_string("study_ancestry", i)) + theme(text = element_text(size=10), axis.text.x = element_text(angle=90, hjust=1)) 
    print(plot + geom_violin())
    
    
    plot <- ggplot(case, aes_string("study_ancestry", i)) + theme(text = element_text(size=10), axis.text.x = element_text(angle=90, hjust=1)) 
    print(plot + geom_violin())
    
    
    plot <- ggplot(control, aes_string("study_ancestry", i)) + theme(text = element_text(size=10), axis.text.x = element_text(angle=90, hjust=1)) 
    print(plot + geom_violin())
    
    
    plot <- ggplot(df, aes_string("study_ancestry", i)) + theme(text = element_text(size=10), axis.text.x = element_text(angle=90, hjust=1)) 
    print(plot + geom_violin(aes(fill=factor(sex))))
    
    
    plot <- ggplot(case, aes_string("study_ancestry", i)) + theme(text = element_text(size=10), axis.text.x = element_text(angle=90, hjust=1)) 
    print(plot + geom_violin(aes(fill=factor(sex))))
    
    
    plot <- ggplot(df, aes_string("study_ancestry", i)) + theme(text = element_text(size=10), axis.text.x = element_text(angle=90, hjust=1)) 
    print(plot + geom_violin(aes(fill=factor(sex))))
    
  }
  
}



```
